name: Platformio
run-name:
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os}}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Core Pio
        run: pip install --upgrade platformio

      - name: Build Project
        run: pio run

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/esp32dev/*.bin
