name: Platformio
run-name:
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA7: ${GITHUB_SHA::7}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os}}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Core Pio
        run: pip install --upgrade platformio

      - name: Build Project
        run: pio run

      - name: Create full firmware
        run: >
          pio pkg exec -p "platformio/tool-esptoolpy" -- esptool.py 
          --chip esp32 merge_bin -o full_${{env.SHA7}}.bin 
          --flash_mode dio --flash_size 4MB
          0x1000  .pio/build/esp32dev/bootloader.bin
          0x8000  .pio/build/esp32dev/partitions.bin
          0x10000 .pio/build/esp32dev/firmware.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/esp32dev/*.bin

      - name: Upload full image
        uses: actions/upload-artifact@v3
        with:
          name: full
          path: full_*.bin
