name: Qemu
run-name:
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QEMU_REL: esp-develop-20220919
    steps:
      - uses: actions/checkout@v3
      - name: Cache qemu
        uses: actions/cache@v3
        with:
            path: |
              qemu/
            key: ${{runner.os}}-qemu
      - name: Download qemu
        env:
          QEMU_DIST: qemu-${{env.QEMU_REL}}.tar.bz2
          QEMU_URL: 'https://github.com/espressif/qemu/releases/download/${{env.QEMU_REL}}'
        run: >
          wget ${{env.QEMU_URL}}/${{env.QEMU_DIST}}
          && tar -xf ${{env.QEMU_DIST}}
          && rm ${{env.QEMU_DIST}}

      - name: Add Path
        run: echo "$GITHUB_WORKSPACE/qemu/bin" >> $GITHUB_PATH

      - name: Call qemu
        run: qemu-system-xtensa -version


