name: Qemu
run-name:
on: [push]

env:
  QEMU_REL: esp-develop-20220919
  QEMU_DIST: qemu-$QEMU_REL.tar.bz2
  QEMU_URL: https://github.com/espressif/qemu/releases/download/$QEMU_REL/$QEMU_DIST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache qemu
        uses: actions/cache@v3
        with:
            path: |
              qemu/
            key: ${{runner.os}}-qemu
      - name: Download qemu
        run: >
          wget $QEMU_URL
          && tar -xf $QEMU_DIST
          && rm $QEMU_DIST

      - name: Add Path
        run: echo "$GITHUB_WORKSPACE/qemu/bin" >> $GITHUB_PATH

      - name: Call qemu
        run: qemu-system-xtensa -version


